import { Container, Header } from "@/components/shared";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "DEPIZZA | Корзина",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#FAF1EE]">
      <Container>
        <Header
          hasCart={false}
          hasSearch={false}
          className="border-b-gray-200"
        />
        {children}
      </Container>
    </main>
  );
}
